[package]
name = "asic-rs-makes-innosilicon"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Innosilicon model identities for asic-rs"

[lints]
workspace = true

[dependencies]
asic-rs-core.workspace = true
serde.workspace = true
strum.workspace = true
ts-rs.workspace = true

[features]
python = ["asic-rs-core/python"]
